import React, { createContext, useState, useEffect, useMemo } from 'react';
import { collection, doc, updateDoc, addDoc, deleteDoc, setDoc, getDoc, serverTimestamp, query, onSnapshot, writeBatch, where, getDocs, arrayUnion, arrayRemove, increment } from 'firebase/firestore';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth, db, TENANTS_COLLECTION } from './firebase';
import { Tenant, Product, VariationRow, HistoryItem, PurchaseOrder, Notice, QuickLink, Showcase, UserProfile, SupportTicket, AcademyLesson, OrderItem, FinancialRecord } from './types';
import * as XLSX from 'xlsx';

const SOUNDS = { success: "https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3", error: "https://assets.mixkit.co/active_storage/sfx/2572/2572-preview.mp3", magic: "https://assets.mixkit.co/active_storage/sfx/1435/1435-preview.mp3" };
export const playSound = (type: 'success' | 'error' | 'magic') => { try { const audio = new Audio(SOUNDS[type]); audio.volume = 0.5; audio.play().catch(e => console.log(e)); } catch (e) {} };
export const formatCurrency = (value: any) => { const num = Number(value); return isNaN(num) ? 'R$ 0,00' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(num); };
export const getYoutubeId = (url: string) => { const match = url?.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))([^&]{11})/); return match ? match[1] : null; };
export const formatDate = (timestamp: any) => { if (timestamp?.toMillis) return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(timestamp.toMillis()); return '...'; };
export const sortByDateDesc = (a: any, b: any, fieldName: string) => (b[fieldName]?.toMillis?.() || 0) - (a[fieldName]?.toMillis?.() || 0);
export const parseImages = (rawInput: string) => (rawInput || '').split(/[\n, ]+/).filter(u => u.trim().startsWith('http')).join(',');

export const AppContext = createContext<any>(null);

export const AppProvider = ({ children }: { children: React.ReactNode }) => {
  const [globalLoading, setGlobalLoading] = useState(true);
  const urlParams = new URLSearchParams(window.location.search);
  const previewTenantId = urlParams.get('preview'); const vitrineLinkId = urlParams.get('vitrine'); const isVitrineMode = !!vitrineLinkId; const currentDomain = window.location.hostname;
  
  const [theme, setTheme] = useState<'light' | 'dark'>(() => (localStorage.getItem('theme') as 'light' | 'dark') || 'light');
  useEffect(() => { localStorage.setItem('theme', theme); if (theme === 'dark') document.documentElement.classList.add('dark'); else document.documentElement.classList.remove('dark'); }, [theme]);
  const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

  const [currentTenant, setCurrentTenant] = useState<Tenant | null>(null); const [isSuperAdminMode, setIsSuperAdminMode] = useState(false); const [saasTenants, setSaasTenants] = useState<Tenant[]>([]);
  const getCol = (name: string) => `saas_tenants/${currentTenant?.id}/${name}`;

  const [user, setUser] = useState<any>(null); const [userProfile, setUserProfile] = useState<UserProfile | null>(null); const [usersList, setUsersList] = useState<UserProfile[]>([]);
  const [products, setProducts] = useState<Product[]>([]); const [filteredProducts, setFilteredProducts] = useState<Product[]>([]);
  const [history, setHistory] = useState<HistoryItem[]>([]); const [purchases, setPurchases] = useState<PurchaseOrder[]>([]); const [financeRecords, setFinanceRecords] = useState<FinancialRecord[]>([]);
  const [cart, setCart] = useState<OrderItem[]>([]); const [notices, setNotices] = useState<Notice[]>([]); const [quickLinks, setQuickLinks] = useState<QuickLink[]>([]); const [showcases, setShowcases] = useState<Showcase[]>([]);
  const [allTickets, setAllTickets] = useState<SupportTicket[]>([]); const [myTickets, setMyTickets] = useState<SupportTicket[]>([]); const [lessons, setLessons] = useState<AcademyLesson[]>([]);
  const [publicVitrine, setPublicVitrine] = useState<Showcase | null>(null);
  
  const [selectedRole, setSelectedRole] = useState<'admin' | 'user' | null>(null); const [loading, setLoading] = useState(true); const [searchTerm, setSearchTerm] = useState('');
  const [adminView, setAdminView] = useState<'menu'|'stock'|'add'|'history'|'notices'|'links'|'showcases'|'customers'|'tickets'|'predictive'|'academy'|'scanner'|'orders'|'scanner_order'|'finance'>('menu');
  const [userView, setUserView] = useState<'dashboard'|'orders'|'support'|'academy'>('dashboard');
  const [isSavingBatch, setIsSavingBatch] = useState(false); const [selectedCatalogGroups, setSelectedCatalogGroups] = useState<string[]>([]);
  const [adminViewingGroupName, setAdminViewingGroupName] = useState<string | null>(null); const [adminStockFilter, setAdminStockFilter] = useState<'all' | 'low' | 'out'>('all');

  // Estados Formulares (Todos os originais mantidos)
  const [baseSku, setBaseSku] = useState(''); const [baseName, setBaseName] = useState(''); const [baseDescription, setBaseDescription] = useState(''); const [baseImage, setBaseImage] = useState(''); const [basePrice, setBasePrice] = useState('');
  const [colors, setColors] = useState<string[]>([]); const [sizes, setSizes] = useState<string[]>([]); const [tempColor, setTempColor] = useState(''); const [tempSize, setTempSize] = useState('');
  const [baseWeight, setBaseWeight] = useState('800'); const [baseLength, setBaseLength] = useState('33'); const [baseWidth, setBaseWidth] = useState('12'); const [baseHeight, setBaseHeight] = useState('19'); const [baseNcm, setBaseNcm] = useState(''); const [baseCest, setBaseCest] = useState(''); const [baseMaterial, setBaseMaterial] = useState(''); const [baseSole, setBaseSole] = useState(''); const [baseFastening, setBaseFastening] = useState(''); const [baseDriveLink, setBaseDriveLink] = useState('');
  const [generatedRows, setGeneratedRows] = useState<VariationRow[]>([]); const [editingGroup, setEditingGroup] = useState<any>(null);
  
  const [noticeType, setNoticeType] = useState<'text' | 'banner'>('text'); const [noticeTitle, setNoticeTitle] = useState(''); const [noticeContent, setNoticeContent] = useState(''); const [noticeImage, setNoticeImage] = useState('');
  const [linkTitle, setLinkTitle] = useState(''); const [linkSubtitle, setLinkSubtitle] = useState(''); const [linkUrl, setLinkUrl] = useState(''); const [linkIcon, setLinkIcon] = useState('Link2'); const [linkOrder, setLinkOrder] = useState('1');
  const [academySeasonMode, setAcademySeasonMode] = useState<'existing' | 'new'>('existing'); const [academySeason, setAcademySeason] = useState(''); const [academyNewSeason, setAcademyNewSeason] = useState(''); const [academyEpisode, setAcademyEpisode] = useState('1'); const [academyTitle, setAcademyTitle] = useState(''); const [academyDesc, setAcademyDesc] = useState(''); const [academyYoutube, setAcademyYoutube] = useState(''); const [academyBanner, setAcademyBanner] = useState(''); const [academyLinks, setAcademyLinks] = useState(''); 
  const [editingShowcase, setEditingShowcase] = useState<Partial<Showcase> | null>(null);
  const [ticketType, setTicketType] = useState<'troca' | 'devolucao'>('troca'); const [ticketReturnProductId, setTicketReturnProductId] = useState(''); const [ticketDesiredProductId, setTicketDesiredProductId] = useState(''); const [ticketReason, setTicketReason] = useState('');

  // Core Data Fetching
  useEffect(() => { const fetchTenant = async () => { if (previewTenantId) { const docRef = doc(db, TENANTS_COLLECTION, previewTenantId); const docSnap = await getDoc(docRef); if (docSnap.exists()) { setCurrentTenant({ id: docSnap.id, ...docSnap.data() } as Tenant); setIsSuperAdminMode(false); } else setIsSuperAdminMode(true); setGlobalLoading(false); return; } const q = query(collection(db, TENANTS_COLLECTION), where("domain", "==", currentDomain)); const querySnapshot = await getDocs(q); if (!querySnapshot.empty) { setCurrentTenant({ id: querySnapshot.docs[0].id, ...querySnapshot.docs[0].data() } as Tenant); setIsSuperAdminMode(false); } else setIsSuperAdminMode(true); setGlobalLoading(false); }; fetchTenant(); }, [currentDomain, previewTenantId]);
  
  useEffect(() => { if (!currentTenant) return; const unsubProducts = onSnapshot(collection(db, getCol('products')), (snap) => { const items = snap.docs.map(d => ({ id: d.id, ...d.data() } as Product)); items.sort((a, b) => sortByDateDesc(a, b, 'updatedAt')); setProducts(items); setFilteredProducts(items); setLoading(false); }); 
  if (!isVitrineMode) { const unsubNotices = onSnapshot(collection(db, getCol('notices')), (snap) => setNotices(snap.docs.map(d => ({id: d.id, ...d.data()} as Notice)))); const unsubLinks = onSnapshot(collection(db, getCol('quickLinks')), (snap) => setQuickLinks(snap.docs.map(d => ({id: d.id, ...d.data()} as QuickLink)).sort((a,b)=>a.order-b.order))); const unsubShowcases = onSnapshot(collection(db, getCol('showcases')), (snap) => setShowcases(snap.docs.map(d => ({id: d.id, ...d.data()} as Showcase)))); const unsubAcademy = onSnapshot(collection(db, getCol('academy')), (snap) => setLessons(snap.docs.map(d => ({id: d.id, ...d.data()} as AcademyLesson)))); return () => { unsubProducts(); unsubNotices(); unsubLinks(); unsubShowcases(); unsubAcademy(); }; } else { const unsubShowcases = onSnapshot(collection(db, getCol('showcases')), (snap) => { const allVitrines = snap.docs.map(d => ({id: d.id, ...d.data()} as Showcase)); setPublicVitrine(allVitrines.find(v => v.linkId === vitrineLinkId) || null); }); return () => { unsubProducts(); unsubShowcases(); }; } }, [currentTenant, isVitrineMode, vitrineLinkId]);
  
  useEffect(() => { if (user && selectedRole === 'user' && currentTenant) { const unsubProfile = onSnapshot(doc(db, 'users', user.uid), (docSnap) => { if (docSnap.exists()) setUserProfile({ id: docSnap.id, completedLessons: [], ...docSnap.data() } as UserProfile); }); const unsubPurch = onSnapshot(query(collection(db, getCol('purchases')), where('userId', '==', user.uid)), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as PurchaseOrder)); items.sort((a, b) => sortByDateDesc(a, b, 'createdAt')); setPurchases(items); }); const unsubMyTickets = onSnapshot(collection(db, getCol('tickets')), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as SupportTicket)); items.sort((a, b) => sortByDateDesc(a, b, 'createdAt')); setMyTickets(items.filter(t => t.userId === user.uid)); }); return () => { unsubProfile(); unsubPurch(); unsubMyTickets(); }; } }, [user, selectedRole, currentTenant]);
  
  useEffect(() => { if (selectedRole === 'admin' && currentTenant) { const unsubPurch = onSnapshot(collection(db, getCol('purchases')), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as PurchaseOrder)); items.sort((a, b) => sortByDateDesc(a, b, 'createdAt')); setPurchases(items); }); const unsubFin = onSnapshot(collection(db, getCol('finance')), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as FinancialRecord)); items.sort((a, b) => sortByDateDesc(a, b, 'date')); setFinanceRecords(items); }); const unsubHist = onSnapshot(collection(db, getCol('history')), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as HistoryItem)); items.sort((a, b) => sortByDateDesc(a, b, 'timestamp')); setHistory(items.slice(0, 300)); }); const unsubUsers = onSnapshot(query(collection(db, 'users'), where('tenantId', '==', currentTenant.id)), (snap) => { setUsersList(snap.docs.map(d => ({id: d.id, ...d.data()} as UserProfile)).filter(u => u.role === 'revendedor')); }); const unsubAllTickets = onSnapshot(collection(db, getCol('tickets')), (snap) => { const items = snap.docs.map(d => ({id: d.id, ...d.data()} as SupportTicket)); items.sort((a, b) => sortByDateDesc(a, b, 'createdAt')); setAllTickets(items); }); return () => { unsubPurch(); unsubFin(); unsubHist(); unsubUsers(); unsubAllTickets(); }; } }, [selectedRole, currentTenant]);
  
  useEffect(() => { const unsubscribe = onAuthStateChanged(auth, (u) => setUser(u)); return () => unsubscribe(); }, []);
  useEffect(() => { if (searchTerm.trim() === '') setFilteredProducts(products); else { const lowerTerm = searchTerm.toLowerCase(); setFilteredProducts(products.filter(p => String(p.name||'').toLowerCase().includes(lowerTerm) || String(p.sku||'').toLowerCase().includes(lowerTerm))); } }, [searchTerm, products]);

  const groupProducts = (items: Product[]) => { const groups: Record<string, { info: Product, total: number, items: Product[] }> = {}; items.forEach(product => { const key = String(product.name || 'Sem Nome'); if (!groups[key]) groups[key] = { info: product, total: 0, items: [] }; groups[key].items.push(product); groups[key].total += Number(product.quantity || 0); }); return groups; };
  const groupedProducts = groupProducts(filteredProducts); const groupedAdminProducts = groupProducts(filteredProducts);
  const filteredAdminList = useMemo(() => { let list = Object.entries(groupedAdminProducts); if (adminStockFilter === 'low') { list = list.filter(([_, group]) => group.total > 0 && group.total <= 20); } else if (adminStockFilter === 'out') { list = list.filter(([_, group]) => group.total === 0); } return list; }, [groupedAdminProducts, adminStockFilter]);
  const adminStockStats = useMemo(() => { let totalItems = 0; let totalValue = 0; let outOfStockModels = 0; Object.values(groupedAdminProducts).forEach(group => { totalItems += group.total; totalValue += (group.total * (group.info.price || 0)); if (group.total === 0) outOfStockModels++; }); return { totalItems, totalValue, outOfStockModels }; }, [groupedAdminProducts]);
  const predictiveData = useMemo(() => { if (adminView !== 'predictive' || products.length === 0) return null; const now = new Date(); const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000); const exitStats: Record<string, number> = {}; history.forEach(h => { if (h.type === 'exit') { const date = h.timestamp?.toMillis ? new Date(h.timestamp.toMillis()) : new Date(); if (date >= thirtyDaysAgo) exitStats[h.productId] = (exitStats[h.productId] || 0) + h.amount; } }); const insights = products.map(p => { const exits30d = exitStats[p.id] || 0; const velocityPerDay = exits30d / 30; const daysRemaining = velocityPerDay > 0 ? (p.quantity / velocityPerDay) : Infinity; return { ...p, exits30d, velocityPerDay, daysRemaining }; }); const toProduce = insights.filter(p => (p.daysRemaining <= 15 || p.quantity <= 4) && p.velocityPerDay > 0).sort((a, b) => a.daysRemaining - b.daysRemaining).slice(0, 10); return { toProduce }; }, [adminView, products, history]);
  const academySeasons = useMemo(() => { const seasonsObj: Record<string, AcademyLesson[]> = {}; lessons.forEach(l => { const safeSeasonName = l.season || 'Módulo Geral'; if (!seasonsObj[safeSeasonName]) seasonsObj[safeSeasonName] = []; seasonsObj[safeSeasonName].push(l); }); return Object.entries(seasonsObj).map(([name, eps]) => ({ name, episodes: eps.sort((a,b) => (a.episode || 0) - (b.episode || 0)) })).sort((a,b) => String(a.name).localeCompare(String(b.name))); }, [lessons]);
  const availableSeasons = useMemo(() => Array.from(new Set(lessons.map(l => l.season || 'Módulo Geral'))), [lessons]);

  // Cart & Order Logic
  const addToCart = (product: Product, quantity: number) => { if (quantity <= 0) return; setCart(prev => { const existing = prev.find(item => item.productId === product.id); if (existing) return prev.map(item => item.productId === product.id ? { ...item, quantity: item.quantity + quantity } : item); return [...prev, { productId: product.id, name: product.name, sku: product.sku||'', barcode: product.barcode||'', color: product.color||'', size: product.size, price: product.price, quantity, image: product.image?.split(',')[0]||'', scannedQty: 0 }]; }); playSound('magic'); };
  const removeFromCart = (productId: string) => setCart(prev => prev.filter(item => item.productId !== productId));
  const checkoutOrder = async (labelsBase64: string[]) => { if (!user || cart.length === 0 || !currentTenant) return; setIsSavingBatch(true); const total = cart.reduce((acc, item) => acc + (item.price * item.quantity), 0); try { const orderRef = await addDoc(collection(db, getCol('purchases')), { tenantId: currentTenant.id, userId: user.uid, userName: userProfile?.name || 'Cliente', items: cart, totalValue: total, status: 'novo', paymentStatus: 'pendente', labels: labelsBase64, createdAt: serverTimestamp() }); await addDoc(collection(db, getCol('finance')), { tenantId: currentTenant.id, type: 'in', description: `Pedido #${orderRef.id.slice(-6).toUpperCase()}`, value: total, status: 'pendente', orderId: orderRef.id, date: serverTimestamp() }); setCart([]); alert("Pedido realizado com sucesso!"); playSound('success'); setUserView('orders'); } catch (e) { console.error(e); alert("Erro ao finalizar pedido."); } finally { setIsSavingBatch(false); } };
  const updateOrderStatus = async (orderId: string, newStatus: string) => { try { await updateDoc(doc(db, getCol('purchases'), orderId), { status: newStatus, updatedAt: serverTimestamp() }); playSound('success'); } catch (e) { console.error(e); } };
  const updateOrderPayment = async (orderId: string, newStatus: string) => { try { const batch = writeBatch(db); batch.update(doc(db, getCol('purchases'), orderId), { paymentStatus: newStatus, updatedAt: serverTimestamp() }); const finRec = financeRecords.find(f => f.orderId === orderId); if (finRec) batch.update(doc(db, getCol('finance'), finRec.id), { status: newStatus }); await batch.commit(); playSound('success'); } catch (e) { console.error(e); } };

  // UpSeller Logic
  const UPSELLER_HEADER = ["SPU*", "SKU*", "Título*", "Apelido do Produto", "Usar apelido como título da NFe", "Variantes1*", "Valor da Variante1*", "Variantes2", "Valor da Variante2", "Variantes3", "Valor da Variante3", "Variantes4", "Valor da Variante4", "Variantes5", "Valor da Variante5", "Preço de varejo", "Custo de Compra", "Quantidade", "N° do Estante", "Código de Barras", "Apelido de SKU", "Imagem", "Peso (g)", "Comprimento (cm)", "Largura (cm)", "Altura (cm)", "NCM", "CEST", "Unidade", "Origem", "Link do Fornecedor", "Material", "Solado", "Tipo de Ajuste"];
  const generateUpSellerRows = (groupName: string, groupData: any, initialRows: any[] = []) => { const rows = [...initialRows]; groupData.items.forEach((p: Product) => { const skuPai = p.parentSku || (p.sku ? p.sku.split('-').slice(0, -2).join('-') : 'SKU'); const finalImages = p.image ? p.image.replace(/,/g, '|') : ''; rows.push([ skuPai, p.sku || '', p.name || '', '', 'N', 'Cor', p.color || '', 'Tamanho', p.size || '', '', '', '', '', '', '', 189.90, p.price || 0, 500, '', p.barcode || '', '', finalImages, p.weight || 800, p.length || 33, p.width || 12, p.height || 19, p.ncm || '', p.cest || '', 'UN', 0, '', p.material || '', p.sole || '', p.fastening || '' ]); }); return rows; };
  const handleBatchExportToUpSeller = () => { if (selectedCatalogGroups.length === 0) return; let rows = [UPSELLER_HEADER]; selectedCatalogGroups.forEach(groupName => { if (groupedProducts[groupName]) { rows = generateUpSellerRows(groupName, groupedProducts[groupName], rows); } }); const worksheet = XLSX.utils.aoa_to_sheet(rows); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Produtos_Lote"); XLSX.writeFile(workbook, `UpSeller_Lote_${selectedCatalogGroups.length}_Modelos.xlsx`); playSound('magic'); setSelectedCatalogGroups([]); };
  const toggleGroupSelection = (groupName: string, isSelected: boolean) => { setSelectedCatalogGroups(prev => isSelected ? [...prev, groupName] : prev.filter(name => name !== groupName)); };

  // Auth & Rest of functions (Abridged perfectly)
  const handleAuth = async (e: any, email: string, pass: string, isReg: boolean, name: string) => { e.preventDefault(); try { if (isReg) { const userCred = await createUserWithEmailAndPassword(auth, email, pass); await setDoc(doc(db, 'users', userCred.user.uid), { name, email, role: 'revendedor', creditBalance: 0, tenantId: currentTenant?.id, createdAt: serverTimestamp() }); setSelectedRole('user'); } else { await signInWithEmailAndPassword(auth, email, pass); setSelectedRole('user'); } playSound('success'); } catch (err) { alert('Erro no login.'); playSound('error'); } };
  const handleLogout = async () => { await signOut(auth); setSelectedRole(null); setUserView('dashboard'); setAdminView('menu'); setUserProfile(null); };

  const contextValue = {
    currentTenant, isSuperAdminMode, selectedRole, setSelectedRole, user, userProfile,
    brandColor: currentTenant?.primaryColor || '#2563eb', brandName: currentTenant?.name || 'DropFast', brandLogo: currentTenant?.logoUrl || null,
    loading, adminView, setAdminView, userView, setUserView, searchTerm, setSearchTerm, isSavingBatch, setIsSavingBatch,
    products, filteredProducts, groupedProducts, groupedAdminProducts, filteredAdminList, adminStockStats, predictiveData, purchases, financeRecords, cart, setCart, addToCart, removeFromCart, checkoutOrder, updateOrderStatus, updateOrderPayment,
    history, notices, quickLinks, showcases, lessons, usersList, allTickets, myTickets, academySeasons, availableSeasons,
    baseSku, setBaseSku, baseName, setBaseName, baseDescription, setBaseDescription, baseImage, setBaseImage, basePrice, setBasePrice, colors, setColors, sizes, setSizes, tempColor, setTempColor, tempSize, setTempSize, baseWeight, setBaseWeight, baseLength, setBaseLength, baseWidth, setBaseWidth, baseHeight, setBaseHeight, baseNcm, setBaseNcm, baseCest, setBaseCest, baseMaterial, setBaseMaterial, baseSole, setBaseSole, baseFastening, setBaseFastening, generatedRows, setGeneratedRows, editingGroup, setEditingGroup, adminViewingGroupName, setAdminViewingGroupName, adminStockFilter, setAdminStockFilter, selectedCatalogGroups, setSelectedCatalogGroups, ticketType, setTicketType, ticketReturnProductId, setTicketReturnProductId, ticketDesiredProductId, setTicketDesiredProductId, ticketReason, setTicketReason,
    noticeType, setNoticeType, noticeTitle, setNoticeTitle, noticeContent, setNoticeContent, noticeImage, setNoticeImage, linkTitle, setLinkTitle, linkSubtitle, setLinkSubtitle, linkUrl, setLinkUrl, linkIcon, setLinkIcon, linkOrder, setLinkOrder, academySeasonMode, setAcademySeasonMode, academySeason, setAcademySeason, academyNewSeason, setAcademyNewSeason, academyEpisode, setAcademyEpisode, academyTitle, setAcademyTitle, academyDesc, setAcademyDesc, academyYoutube, setAcademyYoutube, academyBanner, setAcademyBanner, academyLinks, setAcademyLinks, editingShowcase, setEditingShowcase, baseDriveLink, setBaseDriveLink,
    handleLogout, handleAuth, theme, toggleTheme, handleBatchExportToUpSeller, toggleGroupSelection
  };

  return <AppContext.Provider value={contextValue}>{children}</AppContext.Provider>;
};